stages:
 - build
 - publish

variables:
  DOWNLOAD_ENDPOINT: download.tarantool.io/enterprise
  BUNDLE_VERSION: 1.10.4-24-ge72123b
  ROCK_NAME: sharded-queue

build:
  stage: build
  artifacts:
   name: "$CI_COMMIT_REF_NAME"
   paths:
     - ./release/*all.rock
  tags:
    - docker
  image: centos:7
  before_script:
   - yum -y install epel-release && yum -y update && yum -y install wget git cmake make unzip gcc
   - wget https://tarantool:${DOWNLOAD_TOKEN}@download.tarantool.io/enterprise/tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
   - tar -zxf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz --strip 1
   - source env.sh
   - tarantoolctl rocks install luacheck
   - tarantoolctl rocks install luatest
  script:
   - make build
   - make lint
   - make test
   - ./release.sh

###
### Publish rocks
###
publish-scm-1:
  stage: publish
  tags:
    - docker
  image: centos:7
  only:
    - master
  script:
    - curl --fail -X PUT -F "rockspec=@${ROCK_NAME}-scm-1.rockspec"
      https://${ROCKS_USERNAME}:${ROCKS_PASSWORD}@rocks.tarantool.org

publish-release:
  stage: publish
  tags:
    - docker
  image: centos:7
  only:
    - tags
  script:
    - cd release/
    - curl --fail -X PUT -F "rockspec=@${ROCK_NAME}-${CI_COMMIT_TAG}-1.rockspec"
      https://${ROCKS_USERNAME}:${ROCKS_PASSWORD}@rocks.tarantool.org
    - curl --fail -X PUT -F "rockspec=@${ROCK_NAME}-${CI_COMMIT_TAG}-1.all.rock"
      https://${ROCKS_USERNAME}:${ROCKS_PASSWORD}@rocks.tarantool.org

